// GLOBAL ACTION
export const SCREEN_SIZE = 'SCREEN_SIZE';
export const  LINIER_PROGRES_BAR = 'LINIER_PROGRES_BAR';

// TOAST
export const ADD_TOAST = 'ADD_TOAST';
export const REMOVE_TOAST = 'REMOVE_TOAST';
export const CLEAR_TOASTS = 'CLEAR_TOASTS';

// AUTH
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';

// action types
export const OPEN_SNACKBAR = 'OPEN_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';

export const SHOW_TOAST = 'SHOW_TOAST';
export const HIDE_TOAST = 'HIDE_TOAST';

// USER
export const GET_USER = 'GET_USER';
export const CREATE_USER = 'CREATE_USER';

// PATIENT
export const GET_PATIENT = 'GET_PATIENT';

// SIDEBAR
export const SET_MENU_ITEM_SELECTED = 'SET_MENU_ITEM_SELECTED';
export const SET_IS_COLLAPSE = 'SET_IS_COLLAPSE';

// TRAVEL 
export const GET_TRAVEL_BY_ID = 'GET_TRAVEL_BY_ID';
export const UPDATE_CLINIC_BY_ID = 'UPDATE_CLINIC_BY_ID';

// CABANG
export const GET_CABANG_BY_TRAVELID = 'GET_CABANG_BY_TRAVELID';
export const CREATE_CABANG_BY_TRAVELID = 'CREATE_CABANG_BY_TRAVELID';
export const CREATE_CABANG = 'CREATE_CABANG';
export const DELETE_CABANG = 'DELETE_CABANG';
export const UPDATE_CABANG = 'UPDATE_CABANG';

// WILAYAH INDONESIA
export const GET_PROVINSI = 'GET_PROVINSI';
export const GET_KABUPATEN = 'GET_KABUPATEN';
export const GET_KECAMATAN = 'GET_KECAMATAN';
export const GET_KELURAHAN = 'GET_KELURAHAN';
export const GET_PROVINSI_BY_ID = 'GET_PROVINSI_BY_ID';
export const GET_KABUPATEN_BY_ID = 'GET_KABUPATEN_BY_ID';
export const GET_KECAMATAN_BY_ID = 'GET_KECAMATAN_BY_ID';
export const GET_KELURAHAN_BY_ID = 'GET_KELURAHAN_BY_ID';
export const GET_KABUPATEN_BY_PROVINSI_ID = 'GET_KABUPATEN_BY_PROVINSI_ID';
export const GET_KECAMATAN_KABUPATEN_ID = 'GET_KECAMATAN_KABUPATEN_ID';